In [1]:
import pandas as pd
import os
import shutil
import numpy as np
import copy
import random

In [2]:
seed = 19971204
np.random.seed(seed)
random.seed(seed)

In [3]:
pd.set_option('max_colwidth', 50)

In [3]:
trainSet = pd.read_csv('../dataset/text/train_json.csv', index_col=0)
# devSet = pd.read_csv('../dataset/text/harish_dataset/dev_json.csv', index_col=0)
# testSet = pd.read_csv('../dataset/text/harish_dataset/test_json.csv', index_col=0)

In [5]:
unique_mwes = set(trainSet['mwe'])
len(unique_mwes)

223

In [6]:
# trainSet.loc[trainSet['finegrained'] == 'Meta Usage']
trainSet.head(6)

,id,mwe,literalmeaning,m1,m2,m3,pn,mu,0I/1L,finegrained,prior,at,after,sent,source
0,147,high life,expensive lifestyle,None,None,None,Proper Noun,Meta Usage,1,expensive lifestyle,PSG ace Marquinhos owns this £170k Ferrari - b...,Despite having the riches to afford the high l...,In an interview with the French magazine 'So F...,PSG ace Marquinhos owns this £170k Ferrari - b...,https://www.thesun.co.uk/sport/football/139517...
1,183,birth rate,birth statistic,None,None,None,Proper Noun,Meta Usage,1,birth statistic,Demography expert Piotr Szukalski told Dzienni...,Minister of Family and Social Policy Marlena M...,Commenting on data the state agency Statistics...,Demography expert Piotr Szukalski told Dzienni...,https://www.sandiegouniontribune.com/news/nati...
2,213,home run,house run,baseball run,None,None,Proper Noun,Meta Usage,0,baseball run,Negro Leagues Baseball Museum President Bob Ke...,So Aaron faced the same brutal racism other Bl...,This Black man in the deep South was about to ...,Negro Leagues Baseball Museum President Bob Ke...,https://www.nbcnews.com/news/sports/hank-aaron...
3,26,public service,service helping people,public help,None,None,Proper Noun,Meta Usage,0,public help,The Nakayama Public Service Scholarship is par...,Program leaders said the scholarship defines p...,I think everyone can agree we need to do more ...,The Nakayama Public Service Scholarship is par...,https://today.duke.edu/2021/01/new-nakayama-sc...
4,26,public service,service helping people,public help,None,None,Proper Noun,Meta Usage,1,Proper Noun,He was absolutely right.”,"In the ensuing years, Wennberg might not have ...",Wennberg said he knew when he ran for his sixt...,He was absolutely right.” In the ensuing years...,https://www.rutlandherald.com/news/local/wennb...
5,154,travel guide,guidebook,None,None,None,Proper Noun,Meta Usage,1,Proper Noun,"Today, Forbes Travel Guide's incognito inspect...",Forbes Travel Guide also supports the hospital...,"For more information, please visit partner.for...","Today, Forbes Travel Guide's incognito inspect...",https://markets.businessinsider.com/news/stock...

In [4]:
newTrain = trainSet.drop(trainSet[(trainSet['finegrained'] == 'Proper Noun') | (trainSet['finegrained'] ==  'Meta Usage')].index)

In [11]:
from collections import Counter

Counter(newTrain['0I/1L'])

Counter({1: 1274, 0: 1836})

In [5]:
dict = {}

for mwe, il in list(zip(newTrain['mwe'], newTrain['0I/1L'])):
    if mwe in dict:
        dict[mwe].append(il)
    else:
        new_li=[il]
        dict[mwe]=new_li

In [6]:
frequent_sense = {}

for k, v in dict.items():
    frequent_sense[k] = set(v)

In [ ]:
keys = finegrainedMeaning.keys()
values = finegrainedMeaning.values()

imageSenses = pd.DataFrame(list(zip(keys, values)), columns=['mwe', 'frequent_sense_finegrained'])
imageSenses

mweSenses.to_csv('../dataset/text/imageSenses.csv', index=False)

In [7]:
def rename_file(path, mwe, label):
    try:
        src=os.path.join(path, mwe)
        dst=os.path.join(path, mwe + '_' + str(label))
        os.rename(src,dst)
        return dst
    except:
        print('Error')

In [8]:
newTrain['imagelink'] = 'hey_there_0.jpg'

In [21]:
images_dir = '../dataset/images/classes'

for folder in os.listdir(images_dir):
    mwe_label = folder.split('_')
    mwe, label = ' '.join(mwe_label[:2]), int(mwe_label[2])
    for index, row in newTrain.iterrows():
        train_mwe, train_label = row['mwe'], row['0I/1L']
        # print(train_mwe, mwe, train_label, label)
        if train_mwe == mwe and train_label == label:
            folder_path = os.path.join(images_dir, folder)
            images_list = os.listdir(folder_path)
            filename = random.choice(images_list)
            newTrain.at[index, 'imagelink'] = os.path.join(folder, filename)
            # row['imagelink'] = random.choice(images_list)

In [23]:
newTrain.head()

,id,mwe,literalmeaning,m1,m2,m3,pn,mu,0I/1L,finegrained,prior,at,after,sent,source,imagelink
0,147,high life,expensive lifestyle,None,None,None,Proper Noun,Meta Usage,1,expensive lifestyle,PSG ace Marquinhos owns this £170k Ferrari - b...,Despite having the riches to afford the high l...,In an interview with the French magazine 'So F...,PSG ace Marquinhos owns this £170k Ferrari - b...,https://www.thesun.co.uk/sport/football/139517...,high_life_1\high life_1_2.jpg
1,183,birth rate,birth statistic,None,None,None,Proper Noun,Meta Usage,1,birth statistic,Demography expert Piotr Szukalski told Dzienni...,Minister of Family and Social Policy Marlena M...,Commenting on data the state agency Statistics...,Demography expert Piotr Szukalski told Dzienni...,https://www.sandiegouniontribune.com/news/nati...,birth_rate_1\birth rate_1_12.jpg
2,213,home run,house run,baseball run,None,None,Proper Noun,Meta Usage,0,baseball run,Negro Leagues Baseball Museum President Bob Ke...,So Aaron faced the same brutal racism other Bl...,This Black man in the deep South was about to ...,Negro Leagues Baseball Museum President Bob Ke...,https://www.nbcnews.com/news/sports/hank-aaron...,home_run_0\home run_0_5.jpg
3,26,public service,service helping people,public help,None,None,Proper Noun,Meta Usage,0,public help,The Nakayama Public Service Scholarship is par...,Program leaders said the scholarship defines p...,I think everyone can agree we need to do more ...,The Nakayama Public Service Scholarship is par...,https://today.duke.edu/2021/01/new-nakayama-sc...,public_service_0\public service_0_16.jpg
6,163,swan song,bird song,final performance,None,None,Proper Noun,Meta Usage,0,final performance,The former chief legal officer at Coinbase has...,"Blockchains, fundamentally, are banking becaus...","It is unclear who the incoming president, Joe ...",The former chief legal officer at Coinbase has...,https://www.coindesk.com/occ-chief-brian-brook...,swan_song_0\swan song_0_17.jpg

In [12]:
newTrain.to_csv('../dataset/text/harish_dataset/new_train_json.csv', index=False)

In [85]:
finegrainedMeaning = {}

for _, row in newTrain.iterrows():
    mwe, finegrained, il = row['mwe'], row['finegrained'], row['0I/1L']
    if mwe in finegrainedMeaning:
        # finegrainedMeaning[mwe].add(finegrained)
        finegrainedMeaning[mwe].update({il: finegrained})
    else:
        # fineDict = set()
        # fineSet.add(finegrained)
        # finegrainedMeaning[mwe] = fineSet
        fineDict = {}
        fineDict[il] = finegrained
        finegrainedMeaning[mwe] = fineDict

In [84]:
imageSenses.to_csv('../dataset/text/imageSensesMeaning.csv', index=False)